/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server;
import java.util.ArrayList;
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author freddy
 */
public class FirstView extends javax.swing.JFrame {

    /**
     * Creates new form FirstView
     */
    public FirstView() {
        initComponents();
    }
    Principale p = new Principale();
    Server s = new Server();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        view1welcometext = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        view1servertext = new javax.swing.JTextPane();
        addserverbutton = new javax.swing.JButton();
        urltextfield = new javax.swing.JTextField();
        servernametextfield = new javax.swing.JTextField();
        deleteserverbutton = new javax.swing.JButton();
        view1nextbutton = new javax.swing.JButton();
        masterimage = new javax.swing.JLabel();
        serverimage = new javax.swing.JLabel();
        view1exitbutton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        refreshServersList = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        serversList = new javax.swing.JList<>();
        /*serversList.setModel(new javax.swing.DefaultListModel<String>());
        ArrayList<Server> ls = new ArrayList<Server>();
        ls = p.printServers();
        */

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N

        view1welcometext.setEditable(false);
        view1welcometext.setBackground(new java.awt.Color(154, 142, 130));
        view1welcometext.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        view1welcometext.setText("Hello and Welcome to LogMaster");
        view1welcometext.setToolTipText("");
        jScrollPane1.setViewportView(view1welcometext);

        view1servertext.setEditable(false);
        view1servertext.setBackground(new java.awt.Color(154, 142, 130));
        view1servertext.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, new java.awt.Color(207, 16, 16)));
        view1servertext.setText("Here are your available servers !");
        view1servertext.setAutoscrolls(false);
        jScrollPane2.setViewportView(view1servertext);

        addserverbutton.setBackground(new java.awt.Color(79, 185, 36));
        addserverbutton.setForeground(new java.awt.Color(58, 56, 65));
        addserverbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/add.png"))); // NOI18N
        addserverbutton.setText("Add server");
        addserverbutton.setToolTipText("");
        addserverbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addserverbutton.setOpaque(true);
        addserverbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addserverbuttonMouseClicked(evt);
            }
        });
        addserverbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addserverbuttonActionPerformed(evt);
            }
        });

        urltextfield.setToolTipText("");
        urltextfield.setPreferredSize(new java.awt.Dimension(64, 64));
        urltextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urltextfieldActionPerformed(evt);
            }
        });

        servernametextfield.setToolTipText("");

        deleteserverbutton.setBackground(new java.awt.Color(229, 39, 28));
        deleteserverbutton.setForeground(new java.awt.Color(58, 56, 65));
        deleteserverbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/delete1.png"))); // NOI18N
        deleteserverbutton.setText("Delete server");
        deleteserverbutton.setToolTipText("");
        deleteserverbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteserverbuttonActionPerformed(evt);
            }
        });

        view1nextbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/next.png"))); // NOI18N
        view1nextbutton.setText("            Next");
        view1nextbutton.setToolTipText("");
        view1nextbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view1nextbuttonActionPerformed(evt);
            }
        });

        masterimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/master.png"))); // NOI18N
        masterimage.setToolTipText("");

        serverimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/server1.png"))); // NOI18N
        serverimage.setToolTipText("");

        view1exitbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/exit.png"))); // NOI18N
        view1exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view1exitbuttonActionPerformed(evt);
            }
        });

        jTextPane1.setEditable(false);
        jTextPane1.setText("URL");
        jScrollPane4.setViewportView(jTextPane1);

        jTextPane2.setEditable(false);
        jTextPane2.setText("server name");
        jScrollPane5.setViewportView(jTextPane2);

        refreshServersList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/refresh1.png"))); // NOI18N
        refreshServersList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshServersListActionPerformed(evt);
            }
        });

        jScrollPane6.setViewportView(serversList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(masterimage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(view1exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(serverimage))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(refreshServersList))
                            .addComponent(jScrollPane6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addserverbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(view1nextbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteserverbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(servernametextfield)
                                    .addComponent(urltextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(masterimage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view1exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(serverimage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(refreshServersList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4)
                            .addComponent(urltextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(servernametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addserverbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(deleteserverbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(view1nextbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addserverbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addserverbuttonActionPerformed
        // TODO add your handling code here:
        String url,serverName;
        
        url = urltextfield.getText();
        serverName = servernametextfield.getText();
        p.insertServer(url, serverName);
    }//GEN-LAST:event_addserverbuttonActionPerformed

    private void addserverbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addserverbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addserverbuttonMouseClicked

    private void urltextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urltextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urltextfieldActionPerformed

    private void view1exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view1exitbuttonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_view1exitbuttonActionPerformed

    private void deleteserverbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteserverbuttonActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String url;
        url = urltextfield.getText();
        p.deleteServer(url);
    }//GEN-LAST:event_deleteserverbuttonActionPerformed

    private void refreshServersListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshServersListActionPerformed
        // TODO add your handling code here:
        ArrayList<Server> ls = new ArrayList<Server>();
        ls = p.printServers();//ls is an arraylist of servers
        DefaultListModel dlm1 = new DefaultListModel();//we create a new defaultlistmodel (empty list)
        for(Server srv : ls){
            dlm1.addElement(srv.url);//we add each item of the arraylist in our empty list
            serversList.setModel(dlm1);
            
        }
        
    }//GEN-LAST:event_refreshServersListActionPerformed

    private void view1nextbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view1nextbuttonActionPerformed
        // TODO add your handling code here:
        SecondView secondView = new SecondView();//we create an object from the second view
        String selectedServer = serversList.getSelectedValue();
        ArrayList<String> logsList = new ArrayList<String>();
        logsList= s.listlogs(selectedServer);
        DefaultListModel dlm2 = new DefaultListModel();
        for(String log : logsList){
            dlm2.addElement(log);
            secondView.view2LogsList.setModel(dlm2);//we fill logsList in the second view before making it visible
        }
        //p.disconnect(p.connect());
        secondView.setVisible(true);
 
    }//GEN-LAST:event_view1nextbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addserverbutton;
    private javax.swing.JButton deleteserverbutton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JLabel masterimage;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private javax.swing.JButton refreshServersList;
    private javax.swing.JLabel serverimage;
    private javax.swing.JTextField servernametextfield;
    public static javax.swing.JList<String> serversList;
    private javax.swing.JTextField urltextfield;
    private javax.swing.JButton view1exitbutton;
    private javax.swing.JButton view1nextbutton;
    private javax.swing.JTextPane view1servertext;
    private javax.swing.JTextPane view1welcometext;
    // End of variables declaration//GEN-END:variables
}
