/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server;
import java.*;
import javax.*;
/**
 *
 * @author freddy
 */
public class SecondView extends javax.swing.JFrame {  //JFrame is for he use of graphical interface 

    /**
     * Creates new form SecondView
     */
    public SecondView() {
        initComponents();
    }
    Principale p = new Principale();
    Logs l = new Logs(FirstView.serversList.getSelectedValue());
    LogApache2 apache = new LogApache2(p);
    LogSamba samba = new LogSamba(p);
    SquidLogs squid = new SquidLogs(p);
    SshLog ssh = new SshLog(p);


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        //There is the component we are using in our windows
        jScrollPane2 = new javax.swing.JScrollPane();
        view1servertext = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        view2LogsList = new javax.swing.JList<>();
        view2nextbutton = new javax.swing.JButton();
        view2exitbutton = new javax.swing.JButton();

        //Exit button
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        //Text zones
        view1servertext.setEditable(false);
        view1servertext.setBackground(new java.awt.Color(154, 142, 130));
        view1servertext.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, new java.awt.Color(207, 16, 16)));
        view1servertext.setText("Hey man ! There are several servers available on this server !!!\nPlease choose one to continue!");
        view1servertext.setAutoscrolls(false);
        jScrollPane2.setViewportView(view1servertext);

        jScrollPane1.setViewportView(view2LogsList);

        //Next button
        view2nextbutton.setBackground(new java.awt.Color(237, 172, 84));
        view2nextbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/next.png"))); // NOI18N
        view2nextbutton.setText("            Next");
        view2nextbutton.setToolTipText("");
        view2nextbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view2nextbuttonActionPerformed(evt);
            }
        });

        view2exitbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/exit.png"))); // NOI18N
        view2exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view2exitbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(view2nextbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(view2exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(view2exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(view2nextbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void view2exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view2exitbuttonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_view2exitbuttonActionPerformed

    private void view2nextbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view2nextbuttonActionPerformed
        // TODO add your handling code here:
        String selectedLog = view2LogsList.getSelectedValue();
        
        l.createLogsFiles(selectedLog);
        

        switch(selectedLog){
            case "exemple.apache2.access.log":
                apache.apacheProcess(selectedLog+".txt");
                break;
            case "exemple.linux.auth.sshd.log":
                ssh.sshProcess(selectedLog+".txt");
                break;
                
            case "exemple.samba.host.log":
                samba.sambaProcess(selectedLog+".txt");
                break;
            
            case "exemple.squid.access.log":
                squid.squidProcess(selectedLog+".txt");
                break;
        }
        
        
        System.exit(0);


                
        

        
    }//GEN-LAST:event_view2nextbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecondView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecondView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecondView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecondView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecondView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane view1servertext;
    public javax.swing.JList<String> view2LogsList;
    private javax.swing.JButton view2exitbutton;
    private javax.swing.JButton view2nextbutton;
    // End of variables declaration//GEN-END:variables
}
